jira:
  task_patterns:
    - name: "feature"
      description: "Implementação de nova funcionalidade"
      fields:
        - name: "Objetivo"
          required: true
        - name: "Requisitos"
          required: true
        - name: "Critérios de Aceitação"
          required: true
    - name: "bugfix"
      description: "Correção de bug"
      fields:
        - name: "Descrição do Bug"
          required: true
        - name: "Passos para Reproduzir"
          required: true
        - name: "Comportamento Esperado"
          required: true

github:
  repository: "seu-usuario/seu-repositorio"
  base_branch: "main"
  pr_template: |
    ## Descrição
    {description}

    ## Mudanças
    {changes}

    ## Referência
    Projeto: {project}
    Jira: {jira_key}

openrouter:
  api_key: "${OPENROUTER_API_KEY}"
  model: "openrouter/deepseek/deepseek-chat-v3-0324:free"
  temperature: 0.7
  base_url: "https://openrouter.ai/api/v1"

aider:
  prompt_template: |
    Analise a seguinte task do Jira e sugira as alterações necessárias no código:
    
    Projeto: {project}
    Título: {title}
    Descrição: {description}
    
    Requisitos:
    {requirements}
    
    Por favor, realize qualquer alteração ou criação de código necessárias para implementar esta task no projeto {project}.

projects:
  BMS:
    directory: "C:\\Users\\guilh\\OneDrive\\Documentos\\Personal-Workspace\\boilerplate-microservice-spring"
    description: "Boilerplate Microservice Spring"
    repository: "Gui-Ramos/boilerplate-microservice-spring"
  PROJ2:
    directory: "projetos/projeto2"
    description: "Projeto 2 - Sistema de Estoque"
  PROJ3:
    directory: "projetos/projeto3"
    description: "Projeto 3 - Sistema de RH" 